### ISSUE TITLE
Issues Setting Up Cloned Project

### ISSUE THREAD

**Issue by alexander-alvarez** [cibernox/ember-native-dom-helpers#52]
`yarn install` fails (so I fell back on npm install)
```
error An unexpected error occurred: "https://registry.yarnpkg.com/broccoli-babel-transpiler-6.0.0-alpha.3.tgz: Request failed \"404 Not Found\"".
info If you think this is a bug, please open a bug report with the information provided in "ember-native-dom-helpers/yarn-error.log".
```
`ember s` fails
```
Could not require 'ember-cli-build.js': Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
SyntaxError: Could not require 'ember-cli-build.js': Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at module.exports (ember-native-dom-helpers/node_modules/ember-cli/lib/utilities/find-build-file.js:18:17)
    at Builder.setupBroccoliBuilder (ember-native-dom-helpers/node_modules/ember-cli/lib/models/builder.js:50:21)
    at new Builder (ember-native-dom-helpers/node_modules/ember-cli/lib/models/builder.js:30:10)
```

**Comment by cibernox** [comment]
If you try again should be fine.

**Comment by alexander-alvarez** [comment]
Addressed `ember s` failing in the above PR, still getting the yarn install errors:
```
yarn --version   
0.23.2
```
```
ember --version
ember-cli: 2.13.0-beta.3
node: 4.7.0
os: linux x64

```

**Comment by cibernox** [comment]
Apparently there is a bug in yarn on node 4. Not related with this project.
